/**********************************************************************************************************************
 * \file ASCLIN_Shell_UART.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#if ( defined(__GNUC__) && defined(__TRICORE__) ) \
 || ( defined(__TASKING__) && defined(__CTC__) )/* MCU */
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "drv_tc_asclin.h"

#include "IfxAsclin_Asc.h"
#include "IfxCpu_Irq.h"
#include "IfxAsclin_PinMap.h"

#include "ascii_char.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define UART_BAUDRATE           115200                                  /* UART baud rate in bit/s                  */

#define UART0_PIN_RX            IfxAsclin0_RXA_P14_1_IN                 /* UART receive port pin                    */
#define UART0_PIN_TX            IfxAsclin0_TX_P14_0_OUT                 /* UART transmit port pin                   */
#define UART1_PIN_RX            IfxAsclin1_RXB_P15_5_IN                 /* UART receive port pin                    */
#define UART1_PIN_TX            IfxAsclin1_TX_P15_4_OUT                 /* UART transmit port pin                   */
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/* ASCLIN0 */
/* Declaration of the ASC handle */
static IfxAsclin_Asc_Config ascConfig0;
/* Declaration of the ASC pin */
static const IfxAsclin_Asc_Pins ascPins0 = {
    NULL_PTR,       IfxPort_InputMode_pullUp,     /* CTS pin not used */
    &UART0_PIN_RX,  IfxPort_InputMode_pullUp,     /* RX pin           */
    NULL_PTR,       IfxPort_OutputMode_pushPull,  /* RTS pin not used */
    &UART0_PIN_TX,  IfxPort_OutputMode_pushPull,  /* TX pin           */
    IfxPort_PadDriver_cmosAutomotiveSpeed1
};
/* ASCLIN1 */
/* Declaration of the ASC handle */
static IfxAsclin_Asc_Config ascConfig1;
/* Declaration of the ASC pin */
static const IfxAsclin_Asc_Pins ascPins1 = {
    NULL_PTR,       IfxPort_InputMode_pullUp,     /* CTS pin not used */
    &UART1_PIN_RX,  IfxPort_InputMode_pullUp,     /* RX pin           */
    NULL_PTR,       IfxPort_OutputMode_pushPull,  /* RTS pin not used */
    &UART1_PIN_TX,  IfxPort_OutputMode_pushPull,  /* TX pin           */
    IfxPort_PadDriver_cmosAutomotiveSpeed1
};
/*********************************************************************************************************************/
/*------------------------------------------Internal Function Declarations-------------------------------------------*/
/*********************************************************************************************************************/
static inline void AURIX_TC3_ASCLIN_Init(IfxAsclin_Asc_Config *ascConfig, Ifx_ASCLIN *asclin, IfxAsclin_Asc_Pins *ascPins);
static inline void AURIX_TC3_ASCLIN_PutByte(IfxAsclin_Asc_Config* ascConfig, unsigned char c);
static inline unsigned char AURIX_TC3_ASCLIN_GetByte(IfxAsclin_Asc_Config* ascConfig);
static inline void AURIX_TC3_ASCLIN_DelByte(IfxAsclin_Asc_Config* ascConfig);
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

IfxAsclin_Status init_ASCLIN_UART_MODULE(const IfxAsclin_Asc_Config *config)
{
    Ifx_ASCLIN      *asclinSFR = config->asclin;                        /* pointer to ASCLIN registers*/
    IfxAsclin_Status status    = IfxAsclin_Status_noError;
                                 /* adding register pointer to module handler*/

    IfxAsclin_enableModule(asclinSFR);                                  /* enabling the module*/
    IfxAsclin_setClockSource(asclinSFR, IfxAsclin_ClockSource_noClock); /* disabling the clock*/
    IfxAsclin_setFrameMode(asclinSFR, IfxAsclin_FrameMode_initialise);  /* setting the module in Initialise mode*/
    IfxAsclin_setPrescaler(asclinSFR, config->baudrate.prescaler);      /* sets the prescaler */
    IfxAsclin_setClockSource(asclinSFR, config->clockSource);           /* temporary set the clock source for baudrate configuration*/
    status = (IfxAsclin_Status)IfxAsclin_setBitTiming(asclinSFR,        /* setting the baudrate bit fields to generate the required baudrate*/
        config->baudrate.baudrate,
        config->baudrate.oversampling,
        config->bitTiming.samplePointPosition,
        config->bitTiming.medianFilter);
    IfxAsclin_setClockSource(asclinSFR, IfxAsclin_ClockSource_noClock);              /* disabling the clock again*/

    IfxAsclin_enableLoopBackMode(asclinSFR, config->loopBack);                       /* selecting the loopback mode */
    IfxAsclin_enableParity(asclinSFR, config->frame.parityBit);                      /* setting parity enable */
    IfxAsclin_setParityType(asclinSFR, config->frame.parityType);                    /* setting parity type (odd/even)*/
    IfxAsclin_setStopBit(asclinSFR, config->frame.stopBit);                          /* setting the stop bit */
    IfxAsclin_setShiftDirection(asclinSFR, config->frame.shiftDir);                  /* setting the shift direction */
    IfxAsclin_setDataLength(asclinSFR, config->frame.dataLength);                    /* setting the data length */
    IfxAsclin_setTxFifoInletWidth(asclinSFR, config->fifo.inWidth);                  /* setting Tx FIFO inlet width */
    IfxAsclin_setRxFifoOutletWidth(asclinSFR, config->fifo.outWidth);                /* setting Rx FIFO outlet width */
    IfxAsclin_setIdleDelay(asclinSFR, config->frame.idleDelay);                      /* setting idle delay */
    IfxAsclin_setTxFifoInterruptLevel(asclinSFR, config->fifo.txFifoInterruptLevel); /* setting Tx FIFO level at which a Tx interrupt will be triggered*/
    IfxAsclin_setRxFifoInterruptLevel(asclinSFR, config->fifo.rxFifoInterruptLevel); /* setting Rx FIFO interrupt level at which a Rx interrupt will be triggered*/
    IfxAsclin_setTxFifoInterruptMode(asclinSFR, config->fifo.txFifoInterruptMode);   /* setting Tx FIFO interrupt generation mode */
    IfxAsclin_setRxFifoInterruptMode(asclinSFR, config->fifo.rxFifoInterruptMode);   /* setting Rx FIFO interrupt generation mode */
    IfxAsclin_setFrameMode(asclinSFR, config->frame.frameMode);

    /* Pin mapping */
    const IfxAsclin_Asc_Pins *pins = config->pins;

    if (pins != NULL_PTR)
    {
        IfxAsclin_Cts_In *cts = pins->cts;

        if (cts != NULL_PTR)
        {
            IfxAsclin_initCtsPin(cts, pins->ctsMode, pins->pinDriver);
        }

        IfxAsclin_Rx_In *rx = pins->rx;

        if (rx != NULL_PTR)
        {
            IfxAsclin_initRxPin(rx, pins->rxMode, pins->pinDriver);
        }

        IfxAsclin_Rts_Out *rts = pins->rts;

        if (rts != NULL_PTR)
        {
            IfxAsclin_initRtsPin(rts, pins->rtsMode, pins->pinDriver);
        }

        IfxAsclin_Tx_Out *tx = pins->tx;

        if (tx != NULL_PTR)
        {
            IfxAsclin_initTxPin(tx, pins->txMode, pins->pinDriver);
        }
    }

    IfxAsclin_setClockSource(asclinSFR, config->clockSource); /* select the clock source*/

    IfxAsclin_disableAllFlags(asclinSFR);                     /* disable all flags */
    IfxAsclin_clearAllFlags(asclinSFR);                       /* clear all flags */

    if (config->errorFlags.flags.parityError)
    {
        IfxAsclin_enableParityErrorFlag(asclinSFR, TRUE);
    }

    if (config->errorFlags.flags.frameError)
    {
        IfxAsclin_enableFrameErrorFlag(asclinSFR, TRUE);
    }

    if (config->errorFlags.flags.rxFifoOverflow)
    {
        IfxAsclin_enableRxFifoOverflowFlag(asclinSFR, TRUE);
    }

    if (config->errorFlags.flags.rxFifoUnderflow)
    {
        IfxAsclin_enableRxFifoUnderflowFlag(asclinSFR, TRUE);
    }

    if (config->errorFlags.flags.txFifoOverflow)
    {
        IfxAsclin_enableTxFifoOverflowFlag(asclinSFR, TRUE);
    }

    IfxAsclin_enableRxFifoFillLevelFlag(asclinSFR, TRUE);
    IfxAsclin_enableTxFifoFillLevelFlag(asclinSFR, TRUE);

    /* enable transfers */
    IfxAsclin_enableRxFifoInlet(asclinSFR, TRUE);  // enabling Rx FIFO for recieving
    IfxAsclin_enableTxFifoOutlet(asclinSFR, TRUE); // enabling Tx FIFO for transmitting

    IfxAsclin_flushRxFifo(asclinSFR);              // flushing Rx FIFO
    IfxAsclin_flushTxFifo(asclinSFR);              // flushing Tx FIFO

    return status;
}

/* This function initializes the ASCLIN UART module */
static inline void AURIX_TC3_ASCLIN_Init(IfxAsclin_Asc_Config *ascConfig, Ifx_ASCLIN *asclin, IfxAsclin_Asc_Pins *ascPins)
{
    /* Initialize an instance of IfxAsclin_Asc_Config with default values */
    IfxAsclin_Asc_initModuleConfig(ascConfig, asclin);

    /* Pin configuration */
    ascConfig->pins = ascPins;
    /* Set the desired baud rate */
    ascConfig->baudrate.baudrate = UART_BAUDRATE;

    (void)init_ASCLIN_UART_MODULE(ascConfig); /* Initialize module with above parameters */
}

/* This function sends and receives the string "Hello World!" */
static inline void AURIX_TC3_ASCLIN_PutByte(IfxAsclin_Asc_Config* ascConfig, unsigned char c)
{
    IfxAsclin_write8(ascConfig->asclin, &c, 1U);
    while(IfxAsclin_getTxFifoFillLevel(ascConfig->asclin) != 0);
}

static inline unsigned char AURIX_TC3_ASCLIN_GetByte(IfxAsclin_Asc_Config* ascConfig)
{
    unsigned char c = 0;
    while(IfxAsclin_getRxFifoFillLevel(ascConfig->asclin) == 0);
    IfxAsclin_read8(ascConfig->asclin, &c, 1U);
    return c;
}

static inline void AURIX_TC3_ASCLIN_DelByte(IfxAsclin_Asc_Config* ascConfig)
{
    const unsigned char delChrs[] = { ASCII_CHAR_BS, ASCII_CHAR_DEL, ASCII_CHAR_BS };
    IfxAsclin_write8(ascConfig->asclin, delChrs, 3U);
    while(IfxAsclin_getTxFifoFillLevel(ascConfig->asclin) != 0);
}

/* This function initializes the ASCLIN UART module */
void AURIX_TC3_ASCLIN0_Init(void)
{
    AURIX_TC3_ASCLIN_Init(&ascConfig0, &MODULE_ASCLIN0, &ascPins0);
}

/* This function sends and receives the string "Hello World!" */
void AURIX_TC3_ASCLIN0_PutByte(uint8_t c)
{
    AURIX_TC3_ASCLIN_PutByte(&ascConfig0, (unsigned char)c);
}

uint8_t AURIX_TC3_ASCLIN0_GetByte(void)
{
    return (uint8_t)AURIX_TC3_ASCLIN_GetByte(&ascConfig0);;
}

void AURIX_TC3_ASCLIN0_DelByte(void)
{
    AURIX_TC3_ASCLIN_DelByte(&ascConfig0);
}

/* This function initializes the ASCLIN UART module */
void AURIX_TC3_ASCLIN1_Init(void)
{
    AURIX_TC3_ASCLIN_Init(&ascConfig1, &MODULE_ASCLIN1, &ascPins1);
}

/* This function sends and receives the string "Hello World!" */
void AURIX_TC3_ASCLIN1_PutByte(uint8_t c)
{
    AURIX_TC3_ASCLIN_PutByte(&ascConfig1, (unsigned char)c);
}

uint8_t AURIX_TC3_ASCLIN1_GetByte(void)
{
    return (uint8_t)AURIX_TC3_ASCLIN_GetByte(&ascConfig1);;
}

void AURIX_TC3_ASCLIN1_DelByte(void)
{
    AURIX_TC3_ASCLIN_DelByte(&ascConfig1);
}

#endif /* MCU */
